#Cuando usemos contadores y acumuladores esto te sera util!

#Si queremos operar con una variable y guardar el resultado en la misma variable. Se pueden usar otros operadores
cont = 0
cont = cont + 1
print(cont)
#la linea anterior tambien se puede hacer asi
cont += 1 # el operador antes del = indica que el resultado se guardara en la misma variable
print(cont)

cont -= 1
print(cont)

cont *= 100
print(cont)